version: '3.9'

services:
  db:
    image: postgres:16-alpine3.18
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sccs

  sccs-backend:
    build: ./playground1
    container_name: sccs-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sccs
      SPRING_DATASOURCE_USERNAME: db_admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  sccs-frontend:
    build: ./sccs-client
    container_name: sccs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - sccs-backend
